name: rebuild goochoori-api

on:
  push:
    branches: [main]

jobs:
  rebuild-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Rebuild goochoori-api
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd projects/goochoori-api
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/goochoori
            git pull origin main
            yarn
            /home/ubuntu/.yarn/bin/pm2 stop goochoori-api
            yarn typeorm migration:run
            yarn build
            /home/ubuntu/.yarn/bin/pm2 stop goochoori-api
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.PRIVATE_KEY }}
